[project]
name = "common-dotfiles"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "COM",
    "D",
    "EM",
    "FA",
    "FIX",
    "G003",
    "G004",
    "ISC003",
    "RET505",
    "TD",
    "TRY003",
]
