[project]
name = "common-dotfiles"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "humanize>=4.15.0",
    "playwright>=1.57.0",
    "requests>=2.32.5",
    "termcolor>=3.3.0",
    "tqdm>=4.67.1",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "COM",
    "D",
    "EM",
    "FA",
    "FIX",
    "G003",
    "G004",
    "ISC003",
    "RET505",
    "TD",
    "TRY003",
]
